WebApplication6/WebApplication6/Controllers/ShowUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication6.Repositories;
using WebApplication6.Models;

namespace WebApplication6.Controllers
{
    public class ShowUserController : Controller
    {
        UserRepository userRepository = new UserRepository();
        public IActionResult Index(int id)
        {
            var x = userRepository.TGet(id);
            Login ut = new Login()
            {
                id = x.id,
                Firstname = x.Firstname,
                Lastname = x.Lastname,
                Hours = x.Hours,
                Admin = x.Admin,
                Active = x.Active,
                Username = x.Username,
                Password = x.Password
            };
            return View(ut);
        }
    }
}

WebApplication6/WebApplication6/Controllers/UpdateUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication6.Repositories;
using WebApplication6.Models;


namespace WebApplication6.Controllers
{
    public class UpdateUserController : Controller
    {
        UserRepository userRepository = new UserRepository();
        [HttpPost]
        public IActionResult Index(Login d)
        {
            var x = userRepository.TGet(d.id);
            x.Firstname = d.Firstname;
            x.Lastname = d.Lastname;
            x.Hours = DateTime.Now.ToString("dddd");
            x.Admin = d.Admin;
            x.Active = d.Active;
            x.Username = d.Username;
            x.Password = d.Password;
            userRepository.TUpdate(x);
            return RedirectToAction("Index", "User2");
        }
    }
}

WebApplication6/WebApplication6/Views/ShowUser/Index.cshtml
@model WebApplication6.Models.Login
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/DashBoard.cshtml";
}



<br />
@using (Html.BeginForm("Index", "UpdateUser", FormMethod.Post))
{
<b>id</b><br />
@Html.TextBoxFor(x => x.id)
<br />
<br />
<b>First Name</b><br />
@Html.TextBoxFor(x => x.Firstname)
<br />
<br />
<b>Last Name</b><br />
@Html.TextBoxFor(x => x.Lastname)
<br />
<br />
<b>Hours</b><br />
@Html.TextBoxFor(x => x.Hours)
<br />
<br />
<b>Admin</b><br />
@Html.TextBoxFor(x => x.Admin)
<br />
<br />
<b>Active</b><br />
@Html.TextBoxFor(x => x.Active)
<br />
<br />
<b>User Name</b><br />
@Html.TextBoxFor(x => x.Username)
<br />
<br />
<b>Password</b><br />
@Html.TextBoxFor(x => x.Password)
<br />
<br />
<button class="btn btn-info">Update User</button>
}